name: Zip Make And Pre-Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-pre-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compress make directory to work.zip
        run: |
          cd make
          zip -r ../work.zip .
          cd ..

      - name: Create GitHub Pre-release and upload work.zip
        uses: softprops/action-gh-release@v2
        with:
          tag_name: pre-release-${{ github.run_number }}
          name: 自动预发布 ${{ github.run_number }}
          prerelease: true
          files: work.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
